# fly.toml app configuration file generated for npm-visualizer on 2023-11-08T16:47:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "npm-visualizer"
primary_region = "ams"

[env]
  CACHE_DIR = "/cache"

[mounts]
  source = "npm_visualizer_cache"
  destination = "/cache"

[experimental]
  auto_rollback = true

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 75
    hard_limit = 100

  [[http_service.checks]]
    grace_period = "1s"
    interval = "30s"
    method = "GET"
    timeout = "2s"
    path = "/"
